<?php

namespace Sdz\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use \DateTime;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function findNews()
	{
		$date = new DateTime('NOW');
		$qb = $this->_em->createQueryBuilder(); 
		$qb->select('a')
		->from('SdzBlogBundle:Article', 'a')
		->orderBy('a.date', 'DESC')
		->where('a.date <= :dateDiff')
		->setParameter('dateDiff', $date)
		->setMaxResults('3');

		return $qb->getQuery()
				  ->getResult();
	}
}
