orga_time:
    resource: "@OrgaTimeBundle/Resources/config/routing.yml"
    prefix:   /

sdz_blog:
    resource: "@SdzBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"